ConvertFrom-StringData -StringData @'
	# Main page
	LXPs                      = 本地语言体验包 ( LXPs )
	Menu                      = 菜单
	Update                    = ソリューション ツールボックス
	AddTo                     = 追加
	Done                      = 実施する
	StartVerify               = ダウンロードタスクを確認する
	OK                        = 決定する
	Cancel                    = キャンセル
	Exit                      = 脱落
	AllSel                    = すべて選択
	AllClear                  = すべてクリア
	Operable                  = 操作可能
	Inoperable                = 動作不能
	SwitchLanguage            = 言語を切り替える
	RefreshModules            = モジュールをリロードします
	Choose                    = 選んでください
	FailedCreateFolder        = ディレクトリの作成に失敗しました:
	ToMsg                     = \n   {0} 数秒後、自動的にメインメニューに戻ります。
	ToQuit                    = \n   {0} 数秒でメイン メニューを終了します。
	UserCancel                = ユーザーが操作をキャンセルしました。

	OSVersion                 = 既知のバージョン番号を選択してください
	DownloadAll               = すべてダウンロード
	LXPsFilter                = フィルター
	LXPsDownloadTips          = 既知のバージョン番号を選択するか、対応するバージョン番号を手動で入力してフィルタリングします。番号のみが許可され、次のスペースを含めることはできません：前後のスペース、\\ / : * ? & @ ! "" < > |
	ISO9660TipsErrorSpace     = 含めることはできません：先頭と末尾のスペース
	ISO9660TipsErrorAZ        = 含めることはできません：文字A〜Z
	ISO9660TipsErrorOther     = 含めることはできません：\\ / : * ? & @ ! "" < > |
	ISOLengthError            = 長さは {0} 文字を超えることはできません
	ISOShortError             = 長さは {0} 文字以上にする必要があります
	NoSetLabel                = バージョン番号を手動で入力してください
	LXPsRename                = ルールによって自動的に名前を変更します
	LXPsRenameTips            = 例：LanguageExperiencePack.{*}.Neutral.appx
	LicenseCreate             = License.xml 証明書を作成する
	LicenseCreateTips         = 言語タグに従ってディレクトリに License.xml 証明書ファイルがあるかどうかを確認します。ない場合は、LanguageExperiencePack.{*}.Neutral.appx から現在のディレクトリに license.xml を解放します。

	SaveTo                    = に保存：
	SelectFolder              = ディレクトリを選択
	SelectFolderTips          = 新しいディレクトリを設定すると、[ソースの場所を場所にダウンロードするのと同じです]オプションがオフになります。
	SaveToSync                = 同期ソースの場所は、ダウンロード先の場所と同じです
	SaveToSyncTips            = 新しいフィルタのバージョン番号を設定した後、新しい変更を保存ディレクトリと同じ場所に同期します。カスタマイズした後は、この機能をオフにしてください。
	OpenFolder                = 開けるコンテンツ
	Paste                     = コピーパス
	AdvAppsDetailed           = レポートを生成する
	AdvAppsDetailedTips       = 地域タグで検索し、利用可能なローカル言語エクスペリエンスパックを見つけて詳細を取得し、レポートファイル *.CSV を生成します。
	AddSources                = ソースを追加：
	AddQueue                  = キューを追加：
	YesWork                   = キューにタスクがあります
	NoWork                    = 聞かない
	ProcessSources            = 処理元
	WaitDownloadItem          = Microsoft Store へのリクエストを待っています
	LanguageSelectMark        = 選択した言語タグ
	LanguageSelectChange      = ダウンロードした言語タグを変更する
	MatchDownloadNoNewitem    = 一致しません
	MatchNoDownloadItem       = ダウンロードされていないアイテムを一致させる

	# update
	UpdateServerSelect        = 自動サーバー選択またはカスタム選択
	UpdateServerNoSelect      = 利用可能なサーバーを選択してください
	UpdateSilent              = アップデートが利用可能な場合、サイレントアップデート
	UpdateReset               = このソリューションをリセットする
	UpdateResetTips           = ダウンロードアドレスが利用可能になると、自動的にダウンロードして更新するように強制されます。
	UpdateExit                = 自動更新スクリプトは {0} 秒後に自動的に終了します。
	UpdateCheckServerStatus   = サーバーのステータスを確認します ( 合計 {0} オプション )
	UpdateServerAddress       = サーバーアドレス: {0}
	UpdateServeravailable     = ステータス: 利用可能
	UpdateServerUnavailable   = ステータス: 利用不可
	UpdatePriority            = 優先的に設定されています
	UpdateServerTestFailed    = 失敗したサーバー ステータス テスト
	UpdateQueryingUpdate      = 更新をクエリしています...
	UpdateQueryingTime        = 最新バージョンが利用可能かどうかを確認すると、接続に {0} ミリ秒かかりました。
	UpdateConnectFailed       = リモート サーバーに接続できません。更新が中止されたことを確認してください。
	UpdateMinimumVersion      = 更新プログラムの最小バージョン要件を満たしている、最小必要バージョン: {0}
	UpdateVerifyAvailable     = アドレスが使用可能であることを確認します
	UpdateDownloadAddress     = ダウンロードリンク:
	UpdateAvailable           = 利用可能
	UpdateUnavailable         = 利用不可
	UpdateCurrent             = 現行版: \
	UpdateLatest              = 利用可能な最新バージョン: \
	UpdateNewLatest           = 利用可能な新しいバージョンを見つけました!
	UpdateForce               = 強制的に更新中です。
	UpdateSkipUpdateCheck     = 事前構成されたポリシーでは、自動更新を初めて実行することはできません。
	UpdateTimeUsed            = 使用時間:
	UpdatePostProc            = 後処理
	UpdateNotExecuted         = 未実行
	UpdateNoPost              = 後処理タスクが見つかりません
	UpdateUnpacking           = 開梱
	UpdateDone                = 正常に更新されました！
	UpdateDoneRefresh         = 更新が完了したら、関数処理を実行します。
	UpdateUpdateStop          = 更新のダウンロード中にエラーが発生し、更新プロセスが中止されました。
	UpdateInstall             = この更新プログラムをインストールしますか?
	UpdateInstallSel          = はい、上記の更新がインストールされます\nいいえ、更新はインストールされません
	UpdateNoUpdateAvailable   = \n   利用可能なアップデートはありません。\n\n   あなたは走っている {0}'s Solutions の入手可能な最新バージョン。\n
	UpdateNotSatisfied        = \n   アップデートプログラムの最小バージョン要件を満たしていない、\n\n   最低限必要なバージョン: {0}\n\n   もう一度ダウンロードしてください {1}'s Solutions このツールを更新するには。\n\n   チェックの更新が中止されました。\n

	# Create Update
	UpdateCreate              = アップグレードパッケージを作成する
	UpdateLow                 = 最小要件: \
	UpCreateRear              = 作成後に行う必要があること
	UpCreateASC               = パッケージをアップグレードするためにPGP署名を追加する
	CreateASCPwd              = 証明書のパスワード
	CreateASCAuthor           = 署名者
	CreateASCAuthorTips       = 署名者が選択されていません。
	UpCreateSHA256            = アップグレードパッケージを生成する .SHA-256
	SelectFromError           = エラー：{0}
	Uping                     = 生成
	SkipCreate                = 世代をスキップしますが見つかりません
	ZipStatus                 = 7-Zip がインストールされていません。
	ASCStatus                 = Gpg4win がインストールされていません。
'@