ConvertFrom-StringData -StringData @'
	# Main page
	LXPs                      = 本地語言體驗包 ( LXPs )
	Menu                      = 菜單
	Update                    = 檢查更新
	AddTo                     = 添加
	Done                      = 完成
	StartDownload             = 開始下載
	StartVerify               = 驗證下載任務
	OK                        = 確定
	Cancel                    = 取消
	Exit                      = 退出
	AllSel                    = 選擇所有
	AllClear                  = 清除所有
	Operable                  = 可操作
	Inoperable                = 不可操作
	SwitchLanguage            = 切換語言
	RefreshModules            = 重新加載模塊
	Choose                    = 請選擇
	FailedCreateFolder        = 創建目錄失敗：
	ToMsg                     = \n   {0} 秒後自動返回到主菜單。
	ToQuit                    = \n   {0} 秒後退出主菜單。
	UserCancel                = 用戶已取消操作。

	OSVersion                 = 選擇已知版本號
	DownloadAll               = 下載全部
	LXPsFilter                = 篩選
	LXPsDownloadTips          = 選擇已知版本號，或手動輸入對應的版本號來篩選，只允許數字，不能包含：前後空格、\\ / : * ? & @ ! "" < > |
	ISO9660TipsErrorSpace     = 不能包含：前後空格
	ISO9660TipsErrorAZ        = 不能包含：字母 A-Z
	ISO9660TipsErrorOther     = 不能包含：\\ / : * ? & @ ! "" < > |
	ISOLengthError            = 長度不能大於 {0} 字符
	ISOShortError             = 長度不能小於 {0} 字符
	NoSetLabel                = 請手動輸入版本號
	LXPsRename                = 自動按規則重命名
	LXPsRenameTips            = 示例：LanguageExperiencePack.{*}.Neutral.appx
	LicenseCreate             = 創建 License.xml 證書
	LicenseCreateTips         = 按語言標記檢查目錄下是否有 License.xml 證書文件，如果沒有，從 LanguageExperiencePack.{*}.Neutral.appx 裡釋放 license.xml 到當前目錄下。

	SaveTo                    = 保存到：
	SelectFolder              = 選擇目錄
	SelectFolderTips          = 設置新的目錄後，將關閉“同步來源位置與下載到位置一致”選項。
	SaveToSync                = 同步來源位置與下載到位置一致
	SaveToSyncTips            = 設置新的篩選版本號後，將新的變化同步到保存目錄位置一致，自定義後請關閉該項功能。
	OpenFolder                = 打開目錄
	Paste                     = 複製路徑
	AdvAppsDetailed           = 生成報告
	AdvAppsDetailedTips       = 按區域標記搜索，發現可用的本地語言體驗包後獲取更多詳細信息，生成一份報告文件：*.CSV。
	AddSources                = 添加來源：
	AddQueue                  = 添加隊列：
	YesWork                   = 隊列中有任務
	NoWork                    = 無任務
	ProcessSources            = 處理來源
	WaitDownloadItem          = 等待向 Microsoft Store 發送的請求
	LanguageSelectMark        = 已選擇的語言標記
	LanguageSelectChange      = 修改下載的語言標記
	MatchDownloadNoNewitem    = 未匹配到
	MatchNoDownloadItem       = 匹配未下載項

	# update
	UpdateServerSelect        = 自動選擇服務器或自定義選擇
	UpdateServerNoSelect      = 請選擇可用的服務器
	UpdateSilent              = 有可用更新時，靜默更新
	UpdateReset               = 重置此解決方案
	UpdateResetTips           = 下載地址可用時，強制下載並自動更新。
	UpdateExit                = 自動更新腳本將會在 {0} 秒後自動退出。
	UpdateCheckServerStatus   = 檢查服務器狀態 ( 共 {0} 個可選 )
	UpdateServerAddress       = 服務器地址：{0}
	UpdateServeravailable     = 狀態：可用
	UpdateServerUnavailable   = 狀態：不可用
	UpdatePriority            = 已設置為優先級
	UpdateServerTestFailed    = 未通過服務器狀態測試
	UpdateQueryingUpdate      = 正在查詢更新中...
	UpdateQueryingTime        = 正檢查是否有最新版本可用，連接耗時 {0} 毫秒。
	UpdateConnectFailed       = 無法連接到遠程服務器，檢查更新已中止。
	UpdateMinimumVersion      = 滿足最低更新程序版本要求，最低要求版本：{0}
	UpdateVerifyAvailable     = 驗證地址是否可用
	UpdateDownloadAddress     = 下載地址：
	UpdateAvailable           = 可用
	UpdateUnavailable         = 不可用
	UpdateCurrent             = 當前使用版本: \
	UpdateLatest              = 可用最新版本: \
	UpdateNewLatest           = 發現新的可用版本！
	UpdateForce               = 正在強制進行更新。
	UpdateSkipUpdateCheck     = 預配置策略，不允許首次運行自動更新。
	UpdateTimeUsed            = 所用的時間：
	UpdatePostProc            = 後期處理
	UpdateNotExecuted         = 不執行
	UpdateNoPost              = 未找到後期處理任務
	UpdateUnpacking           = 正在解壓：
	UpdateDone                = 已成功更新！
	UpdateDoneRefresh         = 更新完成後，執行函數處理。
	UpdateUpdateStop          = 下載更新時發生錯誤，更新過程中止。
	UpdateInstall             = 您要安裝此更新嗎？
	UpdateInstallSel          = 是，將安裝上述更新\n否，則不會安裝該更新
	UpdateNoUpdateAvailable   = \n   沒有可用的更新。\n\n   您正在運行 {0}'s Solutions 的最新可用版本。\n
	UpdateNotSatisfied        = \n   不滿足最低更新程序版本要求，\n\n   最低要求版本：{0}\n\n   請重新下載 {1}'s Solutions 的副本，以更新此工具。\n\n   檢查更新已中止。\n

	# Create Update
	UpdateCreate              = 創建升級包
	UpdateLow                 = 最低要求: \
	UpCreateRear              = 創建後需要做些什麼
	UpCreateASC               = 給升級包添加 PGP 簽名
	CreateASCPwd              = 證書密碼
	CreateASCAuthor           = 簽署者
	CreateASCAuthorTips       = 未選擇簽署者。
	UpCreateSHA256            = 給升級包生成 .SHA-256
	SelectFromError           = 錯誤：{0}
	Uping                     = 正在生成
	SkipCreate                = 跳過生成，未找到
	ZipStatus                 = 未安裝 7-Zip。
	ASCStatus                 = 未安裝 Gpg4win。
'@