ConvertFrom-StringData -StringData @'
	# Main page
	LXPs                      = 현지 언어 체험 팩 ( LXPs )
	Menu                      = 메뉴
	Update                    = 업데이트 확인
	AddTo                     = 에 추가
	Done                      = 수행하다
	StartVerify               = 다운로드 작업 확인
	OK                        = 결정
	Cancel                    = 취소
	Exit                      = 그만두 다
	AllSel                    = 모두 선택
	AllClear                  = 모두 지우기
	Operable                  = 실시 가능한
	Inoperable                = 작동 불가
	SwitchLanguage            = 언어 전환
	RefreshModules            = 모듈 다시로드
	Choose                    = 선택하세요
	FailedCreateFolder        = 디렉터리 생성 실패:
	ToMsg                     = \n   {0} 몇 초 후 자동으로 주 메뉴로 돌아갑니다.
	ToQuit                    = \n   {0} 몇 초 안에 메인 메뉴를 종료합니다.
	UserCancel                = 사용자가 작업을 취소했습니다.

	OSVersion                 = 알려진 버전 번호 선택
	DownloadAll               = 모두 다운로드
	LXPsFilter                = 필터
	LXPsDownloadTips          = 알려진 버전 번호를 선택하거나 필터링할 해당 버전 번호를 수동으로 입력하십시오. 숫자만 허용되며 다음을 포함할 수 없습니다. 앞뒤 공백,\\ / : * ? & @ ! "" < > |
	ISO9660TipsErrorSpace     = 포함할 수 없음: 선행 및 후행 공백
	ISO9660TipsErrorAZ        = 포함할 수 없음: 문자 A-Z
	ISO9660TipsErrorOther     = 다음을 포함할 수 없음: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = 길이는 {0} 자를 초과할 수 없습니다
	ISOShortError             = 길이는 {0} 자보다 작을 수 없습니다
	NoSetLabel                = 버전 번호를 수동으로 입력하십시오
	LXPsRename                = 규칙에 따라 자동으로 이름 바꾸기
	LXPsRenameTips            = 예: LanguageExperiencePack.{*}.Neutral.appx
	LicenseCreate             = License.xml 인증서 생성
	LicenseCreateTips         = 언어 태그에 따라 디렉터리에 License.xml 인증서 파일이 있는지 확인하고 없으면 LanguageExperiencePack.{*}.Neutral.appx 에서 현재 디렉터리로 license.xml 을 릴리스합니다.

	SaveTo                    = 저장 위치: \
	SelectFolder              = 디렉토리 선택
	SelectFolderTips          = 새 디렉토리를 설정한 후 "동기화 소스 위치는 다운로드 위치와 동일합니다" 옵션이 꺼집니다.
	SaveToSync                = 동기화 소스 위치는 다운로드 위치와 동일합니다
	SaveToSyncTips            = 새 필터 버전 번호를 설정한 후 새 변경 사항을 저장 디렉토리와 동일한 위치에 동기화하십시오.사용자 정의 후 이 기능을 끄십시오.
	OpenFolder                = 디렉토리 열기
	Paste                     = 복사 경로
	AdvAppsDetailed           = 보고서 생성
	AdvAppsDetailedTips       = 지역 태그로 검색하고 사용 가능한 현지 언어 경험 팩을 찾은 후 자세한 내용을 확인하고 보고서 파일 *.CSV 를 생성합니다.
	AddSources                = 소스 추가: \
	AddQueue                  = 대기열 추가: \
	YesWork                   = 대기열에 작업이 있습니다
	NoWork                    = 묻지 않는다
	ProcessSources            = 처리 소스
	WaitDownloadItem          = Microsoft Store 에 대한 요청을 기다리는 중
	LanguageSelectMark        = 선택한 언어 태그
	LanguageSelectChange      = 다운로드한 언어 태그 수정
	MatchDownloadNoNewitem    = 일치하지 않음
	MatchNoDownloadItem       = 다운로드하지 않은 항목 일치

	# update
	UpdateServerSelect        = 자동 서버 선택 또는 사용자 지정 선택
	UpdateServerNoSelect      = 사용 가능한 서버를 선택하십시오
	UpdateSilent              = 사용 가능한 업데이트가있을 때 자동 업데이트
	UpdateReset               = 이 솔루션 재설정
	UpdateResetTips           = 다운로드 주소를 사용할 수 있으면 자동으로 다운로드 및 업데이트해야합니다.
	UpdateExit                = 자동 업데이트 스크립트는 {0} 초 후에 자동으로 종료됩니다.
	UpdateCheckServerStatus   = 서버 상태 확인 ( 총 {0} 선택 사항 )
	UpdateServerAddress       = 서버 주소: {0}
	UpdateServeravailable     = 상태: 사용 가능
	UpdateServerUnavailable   = 상태: 사용할 수 없음
	UpdatePriority            = 우선 순위로 설정 됨
	UpdateServerTestFailed    = 서버 상태 테스트 실패
	UpdateQueryingUpdate      = 업데이트 쿼리 중 ...
	UpdateQueryingTime        = 최신 버전을 사용할 수 있는지 확인하는 데 연결하는 데 {0} 밀리 초가 걸렸습니다.
	UpdateConnectFailed       = 원격 서버에 연결할 수 없습니다. 업데이트가 중단되었는지 확인하십시오.
	UpdateMinimumVersion      = 최소 업데이트 프로그램 버전 요구 사항, 최소 필수 버전을 충족합니다: {0}
	UpdateVerifyAvailable     = 주소를 사용할 수 있는지 확인
	UpdateDownloadAddress     = 다운로드 링크:
	UpdateAvailable           = 유효한
	UpdateUnavailable         = 없는
	UpdateCurrent             = 현재 버전 : \
	UpdateLatest              = 사용 가능한 최신 버전 : \
	UpdateNewLatest           = 사용 가능한 새 버전을 찾았습니다!
	UpdateForce               = 업데이트가 강제 중입니다.
	UpdateSkipUpdateCheck     = 사전 구성된 정책은 처음으로 자동 업데이트 실행을 허용하지 않습니다.
	UpdateTimeUsed            = 사용 시간 :
	UpdatePostProc            = 후 처리
	UpdateNotExecuted         = 실행되지 않음
	UpdateNoPost              = 사후 처리 작업이 없습니다.
	UpdateUnpacking           = 포장 풀기
	UpdateDone                = 성공적으로 업데이트되었습니다!
	UpdateDoneRefresh         = 업데이트 완료 후 기능 처리를 실행합니다.
	UpdateUpdateStop          = 업데이트를 다운로드하는 동안 오류가 발생하여 업데이트 프로세스가 중단되었습니다.
	UpdateInstall             = 이 업데이트를 설치 하시겠습니까?
	UpdateInstallSel          = 예, 위 업데이트가 설치됩니다.\n아니요, 업데이트가 설치되지 않습니다.
	UpdateNoUpdateAvailable   = \n   사용 가능한 업데이트가 없습니다.\n\n   {0} 솔루션의 최신 버전을 실행 중입니다.\n
	UpdateNotSatisfied        = \n   최소 업데이트 프로그램 버전 요구 사항을 충족하지 않습니다,\n\n   필요한 최소 버전 : {0}\n\n   다시 다운로드하십시오 {1}'s Solutions 사본, 이 도구를 업데이트합니다.\n\n   업데이트 확인이 중단되었습니다.\n

	# Create Update
	UpdateCreate              = 업그레이드 패키지 생성
	UpdateLow                 = 최소 요구 사항: \
	UpCreateRear              = 생성 후 해야 할 일
	UpCreateASC               = 업그레이드 패키지에 PGP 서명 추가
	CreateASCPwd              = 인증서 비밀번호
	CreateASCAuthor           = 서명자
	CreateASCAuthorTips       = 선택한 서명자가 없습니다.
	UpCreateSHA256            = 업그레이드 패키지 생성 .SHA-256
	SelectFromError           = 오류: {0}
	Uping                     = 생성
	SkipCreate                = 생성 건너뛰기, 찾을 수 없음
	ZipStatus                 = 7-Zip 이 설치되어 있지 않습니다.
	ASCStatus                 = Gpg4win 이 설치되어 있지 않습니다.
'@