ConvertFrom-StringData -StringData @'
	# Main page
	LXPs                      = 本地语言体验包 ( LXPs )
	Menu                      = 菜单
	Update                    = 检查更新
	AddTo                     = 添加
	Done                      = 完成
	StartVerify               = 验证下载任务
	OK                        = 确定
	Cancel                    = 取消
	Exit                      = 退出
	AllSel                    = 选择所有
	AllClear                  = 清除所有
	Operable                  = 可操作
	Inoperable                = 不可操作
	SwitchLanguage            = 切换语言
	RefreshModules            = 重新加载模块
	Choose                    = 请选择
	FailedCreateFolder        = 创建目录失败：
	ToMsg                     = \n   {0} 秒后自动返回到主菜单。
	ToQuit                    = \n   {0} 秒后退出主菜单。
	UserCancel                = 用户已取消操作。

	OSVersion                 = 选择已知版本号
	DownloadAll               = 下载全部
	LXPsFilter                = 筛选
	LXPsDownloadTips          = 选择已知版本号，或手动输入对应的版本号来进行筛选，数字长度不少于 5 位，不能包含：英文字母、前后空格、\\ / : * ? & @ ! "" < > | .
	ISO9660TipsErrorSpace     = 不能包含：前后空格
	ISO9660TipsErrorAZ        = 不能包含：字母 A-Z
	ISO9660TipsErrorOther     = 不能包含：\\ / : * ? & @ ! "" < > |
	ISOLengthError            = 长度不能大于 {0} 字符
	ISOShortError             = 长度不能小于 {0} 字符
	NoSetLabel                = 请手动输入版本号
	LXPsRename                = 自动按规则重命名
	LXPsRenameTips            = 示例：LanguageExperiencePack.{*}.Neutral.appx
	LicenseCreate             = 创建 License.xml 证书
	LicenseCreateTips         = 按区域标记搜索，没有 License.xml 证书文件，从 LanguageExperiencePack.{*}.Neutral.appx 里释放 license.xml。

	SaveTo                    = 保存到：
	SelectFolder              = 选择目录
	SelectFolderTips          = 设置新的目录后，将关闭“同步来源位置与下载到位置一致”选项。
	SaveToSync                = 同步来源位置与下载到位置一致
	SaveToSyncTips            = 设置新的筛选版本号后，将新的变化同步到保存目录位置一致，自定义后请关闭该项功能。
	OpenFolder                = 打开目录
	Paste                     = 复制路径
	AdvAppsDetailed           = 生成报告
	AdvAppsDetailedTips       = 按区域标记搜索，发现可用的本地语言体验包后获取更多详细信息，生成一份报告文件：*.CSV。
	AddSources                = 添加来源：
	AddQueue                  = 添加队列：
	YesWork                   = 队列中有任务
	NoWork                    = 无任务
	ProcessSources            = 处理来源
	WaitDownloadItem          = 等待向 Microsoft Store 发送的请求
	LanguageSelectMark        = 已选择的语言标记
	LanguageSelectChange      = 修改下载的语言标记
	MatchDownloadNoNewitem    = 未匹配到
	MatchNoDownloadItem       = 匹配未下载项

	# update
	UpdateServerSelect        = 自动选择服务器或自定义选择
	UpdateServerNoSelect      = 请选择可用的服务器
	UpdateSilent              = 有可用更新时，静默更新
	UpdateReset               = 重置此解决方案
	UpdateResetTips           = 下载地址可用时，强制下载并自动更新。
	UpdateExit                = 自动更新脚本将会在 {0} 秒后自动退出。
	UpdateCheckServerStatus   = 检查服务器状态 ( 共 {0} 个可选 )
	UpdateServerAddress       = 服务器地址：{0}
	UpdateServeravailable     = 状态：可用
	UpdateServerUnavailable   = 状态：不可用
	UpdatePriority            = 已设置为优先级
	UpdateServerTestFailed    = 未通过服务器状态测试
	UpdateQueryingUpdate      = 正在查询更新中...
	UpdateQueryingTime        = 正检查是否有最新版本可用，连接耗时 {0} 毫秒。
	UpdateConnectFailed       = 无法连接到远程服务器，检查更新已中止。
	UpdateMinimumVersion      = 满足最低更新程序版本要求，最低要求版本：{0}
	UpdateVerifyAvailable     = 验证地址是否可用
	UpdateDownloadAddress     = 下载地址：
	UpdateAvailable           = 可用
	UpdateUnavailable         = 不可用
	UpdateCurrent             = 当前使用版本: \
	UpdateLatest              = 可用最新版本: \
	UpdateNewLatest           = 发现新的可用版本！
	UpdateForce               = 正在强制进行更新。
	UpdateSkipUpdateCheck     = 预配置策略，不允许首次运行自动更新。
	UpdateTimeUsed            = 所用的时间：
	UpdatePostProc            = 后期处理
	UpdateNotExecuted         = 不执行
	UpdateNoPost              = 未找到后期处理任务
	UpdateUnpacking           = 正在解压
	UpdateDone                = 已成功更新！
	UpdateDoneRefresh         = 更新完成后，执行函数处理。
	UpdateUpdateStop          = 下载更新时发生错误，更新过程中止。
	UpdateInstall             = 您要安装此更新吗？
	UpdateInstallSel          = 是，将安装上述更新\n否，则不会安装该更新
	UpdateNoUpdateAvailable   = \n   没有可用的更新。\n\n   您正在运行 {0}'s Solutions 的最新可用版本。\n
	UpdateNotSatisfied        = \n   不满足最低更新程序版本要求，\n\n   最低要求版本：{0}\n\n   请重新下载 {1}'s Solutions 的副本，以更新此工具。\n\n   检查更新已中止。\n

	# Create Update
	UpdateCreate              = 创建升级包
	UpdateLow                 = 最低要求: \
	UpCreateRear              = 创建后需要做些什么
	UpCreateASC               = 给升级包添加 PGP 签名
	CreateASCPwd              = 证书密码
	CreateASCAuthor           = 签署者
	CreateASCAuthorTips       = 未选择签署者。
	UpCreateSHA256            = 给升级包生成 .SHA-256
	SelectFromError           = 错误：{0}
	Uping                     = 正在生成
	SkipCreate                = 跳过生成，未找到
	ZipStatus                 = 未安装 7-Zip。
	ASCStatus                 = 未安装 Gpg4win。
'@