ConvertFrom-StringData -StringData @'
	# Main page
	LXPs                      = Local language experience pack ( LXPs )
	Menu                      = Menu
	Update                    = Check for updates
	AddTo                     = Add
	Done                      = Complete
	StartVerify               = Verify download task
	OK                        = OK
	Cancel                    = Cancel
	Exit                      = Exit
	AllSel                    = Select all
	AllClear                  = Clear all
	Operable                  = Operable
	Inoperable                = Inoperable
	SwitchLanguage            = Switch language
	RefreshModules            = Reload the module
	Choose                    = Please select
	FailedCreateFolder        = Failed to create directory: \
	ToMsg                     = \n   Automatically return to the main menu after {0} seconds.
	ToQuit                    = \n   Exit the main menu in {0} seconds.
	UserCancel                = The user has cancelled the operation.

	OSVersion                 = Select a known version number
	DownloadAll               = Download all
	LXPsFilter                = Filter
	LXPsDownloadTips          = Select a known version number, or manually enter the corresponding version number to filter, only numbers are allowed, and cannot contain: spaces before and after, \\ / : * ? & @ ! "" < > |
	ISO9660TipsErrorSpace     = Cannot contain: leading and trailing spaces
	ISO9660TipsErrorAZ        = Cannot contain: Letters A-Z
	ISO9660TipsErrorOther     = Cannot contain: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = The length cannot be greater than {0} characters
	ISOShortError             = The length cannot be less than {0} characters
	NoSetLabel                = Please enter the version number manually
	LXPsRename                = Automatically rename by rules
	LXPsRenameTips            = Example: LanguageExperiencePack.{*}.Neutral.appx
	LicenseCreate             = Create License.xml certificate
	LicenseCreateTips         = Search by region tag, no License.xml certificate file, release license.xml from LanguageExperiencePack.{*}.Neutral.appx.

	SaveTo                    = Save to:
	SelectFolder              = Select directory
	SelectFolderTips          = After setting up a new directory, the "Sync source location is the same as download to location" option will be turned off.
	SaveToSync                = The sync source location is the same as the download to location
	SaveToSyncTips            = After setting a new filter version number, synchronize the new changes to the same location as the save directory. Please turn off this function after customizing.
	OpenFolder                = Open Directory
	Paste                     = Copy path
	AdvAppsDetailed           = Generate report
	AdvAppsDetailedTips       = Search by region tag, get more details after discovering available local language experience packs, generate a report file: *.CSV.
	AddSources                = Add source: \
	AddQueue                  = Add queue: \
	YesWork                   = There are tasks in the queue
	NoWork                    = No task
	ProcessSources            = Processing source
	WaitDownloadItem          = Waiting for a request to the Microsoft Store
	LanguageSelectMark        = Selected language mark
	LanguageSelectChange      = Modify the downloaded language mark
	MatchDownloadNoNewitem    = Not matched
	MatchNoDownloadItem       = Match undownloaded items

	# update
	UpdateServerSelect        = Automatic server selection or custom selection
	UpdateServerNoSelect      = Please select an available server
	UpdateSilent              = When updates are available, update silently
	UpdateReset               = Reset this solution
	UpdateResetTips           = When the download address is available, it is forced to download and update automatically.
	UpdateExit                = The automatic update script will automatically exit after {0} seconds.
	UpdateCheckServerStatus   = Check server status ( total {0} optional )
	UpdateServerAddress       = Server address: {0}
	UpdateServeravailable     = Status: Available
	UpdateServerUnavailable   = Status: Unavailable
	UpdatePriority            = has been set as priority
	UpdateServerTestFailed    = Failed server status test
	UpdateQueryingUpdate      = Querying and updating...
	UpdateQueryingTime        = Checking if the latest version is available,\n   the connection took {0} milliseconds.
	UpdateConnectFailed       = Unable to connect to remote server, check update has been aborted.
	UpdateMinimumVersion      = Meet the minimum update program version requirements,\n   the minimum required version: {0}
	UpdateVerifyAvailable     = Verify that the address is available
	UpdateDownloadAddress     = Download link: \
	UpdateAvailable           = Available
	UpdateUnavailable         = Unavailable
	UpdateCurrent             = \  Currently used version: \
	UpdateLatest              = Latest version available: \
	UpdateNewLatest           = Found a new version available!
	UpdateForce               = An update is being forced.
	UpdateSkipUpdateCheck     = The pre-configured policy does not allow automatic updates to be run for the first time.
	UpdateTimeUsed            = Time used: \
	UpdatePostProc            = Post-processing
	UpdateNotExecuted         = Not executed
	UpdateNoPost              = No post-processing task found
	UpdateUnpacking           = Unpacking
	UpdateDone                = Successfully updated!
	UpdateDoneRefresh         = After the update is complete, execute function processing.
	UpdateUpdateStop          = An error occurred while downloading the update and the update process was aborted.
	UpdateInstall             = Do you want to install this update?
	UpdateInstallSel          = Yes, the above update will be installed\nNo, the update will not be installed
	UpdateNoUpdateAvailable   = \n   No updates available.\n\n   You are running the latest available version of {0}'s Solutions.\n
	UpdateNotSatisfied        = \n   Does not meet the minimum update program version requirements,\n\n   Minimum required version: {0}\n\n   Please download a copy of {1}'s Solutions again to update this tool.\n\n   Check for update has been aborted.\n

	# Create Update
	UpdateCreate              = Create upgrade package
	UpdateLow                 = Minimum requirement: \
	UpCreateRear              = What needs to be done after creation
	UpCreateASC               = Add PGP signature to the upgrade package
	CreateASCPwd              = Certificate password:
	CreateASCAuthor           = Signatory
	CreateASCAuthorTips       = No signers selected.
	UpCreateSHA256            = Generate .SHA-256 for the upgrade package
	SelectFromError           = Error: {0}
	Uping                     = Generating
	SkipCreate                = Skip generation, not found
	ZipStatus                 = 7-Zip is not installed.
	ASCStatus                 = Gpg4win is not installed.
'@